server: 
  port: 9090
spring: 
  mvc: 
    static-path-pattern: /**
  resources: 
    static-locations: classpath:/static/
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/jwt?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  http:
    multipart:
      max-file-size: 4Mb
      max-request-size: 10Mb
      
security:
  oauth2:
    resource:
      filter-order: 3
      service-id: users-info
      
logging:
  pattern:
    console: "%d - %msg%n"
  file: logs/kfwl.log
  level: 
    com.kfwl: DEBUG
    root: INFO
    java.sql.PreparedStatement: DEBUG
    java.sql.Statement: DEBUG 
    java.sql.Connection: DEBUG 
    java.sql.ResultSet: DEBUG